pipeline {
    agent { label 'agent1' }
    stages {
        stage('Install & Start Apache2') {
            steps {
                sh 'sudo apt install apache2 -y'
                sh 'sudo systemctl start apache2'
            }
        }
        stage('Set env') {
            steps {
                sh 'echo "test" >> .env'
                sh 'cat .env'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
